name: video_cutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  ffmpeg_kit_min_gpl: ^6.0.3+2-LTS
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  video_player: ^2.7.0
  http: ^1.2.1 

  cached_network_image: ^3.3.0
  dio: ^5.3.2
  percent_indicator: ^4.2.2
  flutter_native_splash: ^2.3.1
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2












  flutter_background: ^1.3.0+1
  flutter_local_notifications: ^19.3.1
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.3.1
  workmanager: ^0.8.0
  wakelock_plus: ^1.3.2
  path: ^1.8.2
  async: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
